
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stg_development
  username: <%= ENV.fetch('STG_DATABASE_USERNAME', nil) %>
  password: <%= ENV.fetch('STG_DATABASE_PASSWORD', nil) %>

test:
  <<: *default
  database: stg_test

production:
  <<: *default
  database: stg_production
  username: stg
  password: <%= ENV.fetch('STG_DATABASE_PASSWORD', nil) %>